[tool.poetry]
name = "isdb-scanner"
version = "1.0.0"
description = ""
authors = ["tsukumi <tsukumijima@users.noreply.github.com>"]
license = "MIT"
readme = "Readme.md"

[tool.poetry.dependencies]
python = "^3.10"
ariblib = {url = "https://github.com/tsukumijima/ariblib/releases/download/v0.1.3/ariblib-0.1.3-py3-none-any.whl"}
devtools = "^0.11.0"
pydantic = "^2.1.1"
ruamel-yaml = "^0.17.32"
typer = {extras = ["all"], version = "^0.9.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
